### ISSUE TITLE
Refactor tests parameters and fixtures

### ISSUE THREAD

**Issue by jordaneremieff** [jordaneremieff/mangum#106]
The tests are a bit difficult to understand at the moment. I think the parameterization and fixtures could be modified to make it easier to make the behaviour more clear, docstrings are probably a good idea too.

**Comment by Vlad-Radz** [comment]
May I take this one?

**Comment by jordaneremieff** [comment]
@Vlad-Radz sure! :)

**Comment by jordaneremieff** [comment]
@Vlad-Radz are you still interested in taking this up? I was thinking of looking into it again, but don't want to step on your toes if you are already working on it or still interested in doing so.

If you still want to but don't have time, then it can wait until you're able to look into it. No pressure, but please let me know when you can. :)

**Comment by Vlad-Radz** [comment]
Hello @jordaneremieff, thanks for asking! Indeed, I started to check the overall codebase in general and tests in particular this week, in order to understand it better. Right now I have time at the work, but if this will change, I will let you know.

**Comment by Vlad-Radz** [comment]
Hello, sorry for being inactive for some time. I finally started to improve testing code base by adding docstrings and even new test cases. Also I have an idea for some new fixtures. You can see the progress here: https://github.com/jordaneremieff/mangum/compare/main...Vlad-Radz:chore/106_improve_tests

**Comment by four43** [comment]
Does #170 close this to your liking too? I did leave some of your old fixtures in there as to build a little confidence that I didn't totally break everything :)

**Comment by jordaneremieff** [comment]
I'm going to close this as a specific issue, but any contributions to improve the tests are always welcomed.
