### ISSUE TITLE
Local dev server

### ISSUE THREAD

**Issue by jordaneremieff** [jordaneremieff/mangum#123]
I think this would be mostly useful for developing Mangum itself, but it could be useful for application developers. Currently I've relied on [Serverless Offline](https://github.com/dherault/serverless-offline) to test deployments, but this requires a Serverless Framework configuration and gives me a lot more than I need for certain debugging tasks.

Essentially what I think needs to be done is provide a layer to convert normal HTTP/WebSocket requests into AWS events and feed that to the adapter, then emulate the AWS response. Can probably create some tooling that can be re-used in the tests as well.

**Comment by andrianowinatra** [comment]
Is it not possible to rely on [localstack?](https://github.com/localstack/localstack)

**Comment by jordaneremieff** [comment]
@andrianowinatra I'm not very familiar with this library, but one thing I noticed in the README is that it would require a paid plan for WebSocket support. I'm primarily wanting this for WebSockets development without needing any additional configuration or overhead, because I want a way to quickly see how the adapter and ASGI requests<->response behaviour is working before committing to any significant integration/functional tests.

**Comment by Kludex** [comment]
Maybe we can get a plan talking with the localstack team.

PR is welcome to add `localstack` to the repository.

**Comment by pkucmus** [comment]
I mentioned it [there](https://github.com/florimondmanca/awesome-asgi/issues/100) but got no reply. I'll try here then.

Will [Smyth](https://mirumee.github.io/smyth/) fill this gap?

It's not a direct replacement for serverless, but helps us with local development a lot for months now.
