### ISSUE TITLE
Move WebSocket support into separate project

### ISSUE THREAD

**Issue by jordaneremieff** [jordaneremieff/mangum#127]
I’m wondering if it might be a good idea to focus on WebSocket support in a separate repo and have Mangum primarily focus on HTTP.

The HTTP support is pretty much “done”, and my guess is that this is the primary use-case for most users. WebSocket support has been changing quite a bit, and I don’t think it is being used very much.

If anyone has opinions, please let me know, otherwise I think I’ll pull websocket support out into a separate package.

**Comment by jordaneremieff** [comment]
Actually, nevermind. I thought it about more, this isn't a good idea.

**Comment by jordaneremieff** [comment]
Actually, this might have been a good idea. 

The broadcast support that I want to include in here is a fairly large project to complete, and I don't think the WebSocket implementation is as useful without it. I don't have as much time as I did when I initially started on it, and I don't want to block other changes being merged/release or maintain parity between my WIP branches and main.

My initial idea for a 1.0 release would be solid HTTP and WebSocket (/w broadcast) support, but the maintenance burden of supporting both in one package doesn't seem worth it.

I think I'll remove WebSocket support in a new PR.

**Comment by jordaneremieff** [comment]
Done. I'll think about how I might document a path forward here if anyone is interested in API Gateway WebSocket support in the future, but not sure at the moment. I think a separate project is best.

**Comment by koxudaxi** [comment]
@jordaneremieff 
My team wants to use API Gateway WebSocket.
We are testing it with Magnum.
Did you have a plan for a new project?

**Comment by jordaneremieff** [comment]
@koxudaxil I am still thinking about how to best approach it, but yes, I will be creating a separate project. I’ll create a new ticket today with my thoughts/roadmap about the future of WebSocket support to track this effort, because my goal is to use this separate project to develop the feature and later migrate it back into Mangum itself.

**Comment by koxudaxi** [comment]
Thank you for your reply.
I'm waiting for the next action.
I'm busy this month, But, I hope to test it or, discuss it with you.
