### ISSUE TITLE
API Gateway returns timeout error after conect to WebSockets endpint

### ISSUE THREAD

**Issue by koxudaxi** [jordaneremieff/mangum#128]
API gateway returns an error of timeout after 30 seconds when I connect on WebSocket.
I can drop the error. But, I don't know why the error happens.
the error message is "Endpoint request timed out".

**Comment by jordaneremieff** [comment]
@koxudaxi thanks for reporting the issue. 

Could you drop the error here? I'll take a look into reproducing and try to resolve as part of the refactor PR.

**Comment by koxudaxi** [comment]
@jordaneremieff 

> Could you drop the error here?

WebSocket Client get this error.
`{"message": "Endpoint request timed out", "connectionId":"yyyyyyyyyyyy=", "requestId":"xxxxxxxxxx="}`

Thank you very much

**Comment by jordaneremieff** [comment]
@koxudaxi I don't think I am able to debug this without knowing more about application and deployment. There is some info about the API Gateway events documented [here](https://mangum.io/websockets/#api-gateway-events), it could be that the `$connect` event route is not defined. Or perhaps there is something in the application logic causing it to hang?

In any case, I think the adapter probably _should_ implement some behaviour around handling timeouts. If you are able to provide a minimal example of an application (and perhaps some detail on the API Gateway routes) that can be used to reproduce this error, then I would use that as a starting point for timeout handling (or maybe additional documentation depending on the cause).

**Comment by koxudaxi** [comment]
@jordaneremieff 
I might mistake the event route. I will check it. 
I close this issue now.
If I can't resolve the error then, I will re-open this issue and show you an example code.

We may need to write an example in Mangum document as the AWS setting(Cloud Formation or CDK or etc) to understand it easily. 

Thank you very much.
