### ISSUE TITLE
Use Github actions

### ISSUE THREAD

**Issue by jordaneremieff** [jordaneremieff/mangum#131]

**Comment by simonw** [comment]
I have a pull request open with a direct port of the current `.travis.yml` configuration to GitHub Actions.

Is that what you were looking for here?

**Comment by simonw** [comment]
I use Actions to publish my releases to PyPI too - e.g. https://github.com/simonw/datasette-graphql/blob/main/.github/workflows/publish.yml - happy to include that if it would be useful (you'll need to set a `PYPI_TOKEN` secret for that to work).

**Comment by jordaneremieff** [comment]
@simonw awesome! Yep, this is exactly what I wanted to accomplish for this one. If you could add include the publish workflow as well that would be great too.

Thank you!

**Comment by simonw** [comment]
OK, added that to the pull request.

It works based on creating GitHub releases - which are attached to tags.

You will need to set a PYPI_TOKEN secret for the repo. You can generate a token that is scoped to only be able to release Mangum using the interface at https://pypi.org/manage/account/token/

**Comment by jordaneremieff** [comment]
Merged https://github.com/jordaneremieff/mangum/pull/136
