### ISSUE TITLE
Brotli Support

### ISSUE THREAD

**Issue by burritoIand** [jordaneremieff/mangum#139]
Hello, I just created an issue over in https://github.com/fullonic/brotli-asgi/issues/12, which looks familiar from https://github.com/jordaneremieff/mangum/issues/90.

Would the place to add brotli support to fix this bug be here in Mangum?

**Comment by fullonic** [comment]
Looks like the issue is here: https://github.com/jordaneremieff/mangum/blob/dc16f7f32d16d2f95b2fdceba6995404b16bc6e0/mangum/protocols/http.py#L158
I did a PR that solves your issue https://github.com/jordaneremieff/mangum/pull/140. May you test it? thanks
