### ISSUE TITLE
How to configure it to work with API Gateway's stage URLs? (Can't get FastAPI Auto docs to work)

### ISSUE THREAD

**Issue by mojimi** [jordaneremieff/mangum#142]
When you're using API Gateway without custom domain, your URL will look something like this :
`
https://123.execute-api.ap-southeast-2.amazonaws.com/dev`

But `/dev/` actually translates to `/ ` in the lambda handler

So, because of this I could't get FastAPI auto docs to work, because it will try to get the json file via javascript through the `/openapi.json` relative URL, which will translate to` https://123.execute-api.ap-southeast-2.amazonaws.com/openapi.json` instead of `https://123.execute-api.ap-southeast-2.amazonaws.com/dev/openapi.json`.

Is there a way to workaround this without using custom domain?

**Comment by jordaneremieff** [comment]
@mojimi Hello.

I think you should be able to use the `api_gateway_base_path` parameter for this:

```python
handler = Mangum(app, api_gateway_base_path="/dev")
```

If this does not work, then I will need more information about your deployment.

**Comment by mojimi** [comment]
> 
> 
> @mojimi Hello.
> 
> I think you should be able to use the `api_gateway_base_path` parameter for this:
> 
> ```python
> handler = Mangum(app, api_gateway_base_path="/dev")
> ```
> 
> If this does not work, then I will need more information about your deployment.

That didn't work actually, the problem really is on the frontend, I will try to setup a minimal working example and post here, but there really isn't anything to it

**Comment by jordaneremieff** [comment]
@mojimi I tried to recreate the issue but wasn't able to. If you can post something to reproduce I can take another look.

**Comment by theoturner** [comment]
I also had this issue and fixed it by setting `openapi_prefix` in the FastAPI constructor, e.g. for the above:
```py
app = FastAPI(openapi_prefix="/dev")
```
This will likely cause the same error in your local environment, so you can use an environment variable with `""` as the default, i.e.
```py
app = FastAPI(openapi_prefix=os.environ.get("OPENAPI_PREFIX", "")
```
