### ISSUE TITLE
Slash at end of endpoint

### ISSUE THREAD

**Issue by sergiors** [jordaneremieff/mangum#151]
I've been updated to version `0.10.0` and suddenly all my endpoints on custom domain doesn't work more. I had to add `/` at end of url to back to work.

Is it a normal or a bug?

**Comment by jordaneremieff** [comment]
@sergiors there was a change merged as part of https://github.com/jordaneremieff/mangum/issues/137 to conditionally prefix the base path in `0.10.0`, though it's unclear if that would have caused the behavior you're describing.

Can you please provide the following:

- Example of your previous configuration
- Example of your current configuration
- Previous version of Mangum before `0.10.0`

**Comment by jordaneremieff** [comment]
Closing this off because I don't think there is a bug or anything unexpected at this point, but feel free to follow-up with additional comments.

**Comment by tobiasfeil** [comment]
I had a bug today that may be related. When I have a router with an API prefix, the root path of that router acts different locally - running on uvicorn - vs. when it's deployed on AWS. Consider this scenario:
```
router = APIRouter(prefix='/myRouter')

@router.get('/')
...
```
Then, locally, it works with or without a trailing slash.

But on AWS, it only works with the trailing slash.

Conversely, if I change it to `@router.get('')`, it works without the slash remotely, but *only* without the slash, while both cases still work locally.
