### ISSUE TITLE
[Question] What is a purpose of using asyncio.Queue() in HTTPCycle

### ISSUE THREAD

**Issue by toidi** [jordaneremieff/mangum#154]
https://github.com/jordaneremieff/mangum/blob/8763b9736a8ef60d16e10a204617f9b25fcd6a61/mangum/protocols/http.py#L45-L46

**Comment by jordaneremieff** [comment]
@toidi Hello, I'm not sure if I understand your question. The description in the docstring seems clear to me, but perhaps it could be reworded?

The queue is used to communicate [ASGI message events](https://asgi.readthedocs.io/en/latest/specs/www.html) between the application and adapter. The [receive](https://github.com/jordaneremieff/mangum/blob/8763b9736a8ef60d16e10a204617f9b25fcd6a61/mangum/protocols/http.py#L97) and [send](https://github.com/jordaneremieff/mangum/blob/8763b9736a8ef60d16e10a204617f9b25fcd6a61/mangum/protocols/http.py#L103) methods are implemented to handle events according to the ASGI [specification](https://asgi.readthedocs.io/en/latest/specs/main.html#events).

That said, this could be implemented without using a queue - which is actually something I've been meaning to do at some point.

**Comment by toidi** [comment]
I mean, assuming the way Lambda works - it only sends one event(HTTP request) per invocation.

Python lambda internal are available here https://github.com/aws/aws-lambda-python-runtime-interface-client/

In that scenario async framework barely makes sense, but that's not a topic I'd like to discuss.

I didn't understand what caused the requirement of adding complexity with queuing. Weren't regular async/await primitives enough for the case?

**Comment by toidi** [comment]
Thanks for the explanation. After reading the specification I find it makes sense.
