### ISSUE TITLE
[Feature Request] Support for custom loggers

### ISSUE THREAD

**Issue by aksel** [jordaneremieff/mangum#156]
We are using the logger from [aws-lambda-powertools-python](https://awslabs.github.io/aws-lambda-powertools-python/core/logger/). It's a logging tool from AWS, that can be quite helpful when it comes to debugging, especially when using CloudWatch Log Insights.

I would like to use this logger with Mangum as well.

I was thinking the constructor could accept a `logger_class` parameter, which when set is used instead of `logging.getLogger`. Alternatively, following `logging.setLoggerClass`, a function that can set which logger is used in `adapter.get_logger`.

I tried using `logging.setLoggerClass` directly, but that results in a RecursionError; the AWS logger doesn't inherit `logging.Logger` properly, but instead instantiates an internal logger from `logging.getLogger`.
If you think I should report the recursion error on the [AWS repo](https://github.com/awslabs/aws-lambda-powertools-python) instead, please let me know. I am quite new to Python, and don't know whether this behavior acceptable.

**Comment by tuukkamustonen** [comment]
I'm also wondering about the logging.

You can adjust the logging level only, so does it only do this:

```py
logging.getLogger("mangum").setLevel(...)
```

...or something else, too?

Not sure, but it seems that it would inject a stdout handler, too? Not sure, I need to investigate.

Would be nice to completely define (or skip) logging, and then instead manually adjust it however you want.

**Comment by tuukkamustonen** [comment]
> You can adjust the logging level only, so does it only do this:
> 
> ```python
> logging.getLogger("mangum").setLevel(...)
> ```

To answer myself, seems like that's exactly what it does: https://github.com/jordaneremieff/mangum/blob/main/mangum/adapter.py#L66-L67

So it doesn't inject a handler, that must come from somewhere else of my app. Sorry for noise.

But yeah, BYOL (bring your own logging :P) would be nice!

**Comment by koxudaxi** [comment]
I feel `aws-lambda-powertools-python` is useful-tools for Lambda.
But, I have not used the logger of `aws-lambda-powertools-python` yet.
I will confirm the behavior of it when I get the time next week.

**Comment by jordan-cote** [comment]
> I will confirm the behavior of it when I get the time next week.
@koxudaxi Any updates on this?

**Comment by koxudaxi** [comment]
@jordan-cote 
Thank you for reminding me.
`aws_lambda_powertools.Logger` can accept custom logger name as `service` argument.
And, The logger will be created for mangum.
If `aws_lambda_powertools.Logger(service="mangum)` is called before `Mangum()` is run.
```python
from mangum import Mangum
from fastapi import FastAPI

from aws_lambda_powertools import Logger
logger = Logger(service="mangum")

app = FastAPI()

handler = Mangum(app)

handler.logger.error("example from mangum")
logger.error("exammple from powertools")

```

## Output
```
{"level": "ERROR", "location": "<module>:12", "message": "example from mangum", "timestamp": "2021-03-11 23:08:56,758", "service": "mangum", "sampling_rate": 0.0}
{"level": "ERROR", "location": "<module>:13", "message": "exammple from powertools", "timestamp": "2021-03-11 23:08:56,758", "service": "mangum", "sampling_rate": 0.0}
```

**Comment by koxudaxi** [comment]
Also, We can change `log_level` by Mangum(..., log_level=<log_level>)

There is an example for `debug`.
```python
from mangum import Mangum
from fastapi import FastAPI

from aws_lambda_powertools import Logger
logger = Logger(service="mangum")

app = FastAPI()

handler = Mangum(app, log_level="debug")

handler.logger.error("example from mangum")
logger.error("exammple from powertools")

if __name__ == '__main__':
    from collections import defaultdict
    mock_event = defaultdict(dict)
    handler(mock_event, None)

```


```python
{"level": "ERROR", "location": "<module>:11", "message": "example from mangum", "timestamp": "2021-03-11 23:50:22,356", "service": "mangum", "sampling_rate": 0.0}
{"level": "ERROR", "location": "<module>:12", "message": "exammple from powertools", "timestamp": "2021-03-11 23:50:22,356", "service": "mangum", "sampling_rate": 0.0}
{"level": "DEBUG", "location": "__call__:85", "message": "Event received.", "timestamp": "2021-03-11 23:50:22,356", "service": "mangum", "sampling_rate": 0.0}
{"level": "INFO", "location": "startup:176", "message": "Waiting for application startup.", "timestamp": "2021-03-11 23:50:22,357", "service": "mangum", "sampling_rate": 0.0}
{"level": "INFO", "location": "send:129", "message": "LifespanCycleState.STARTUP:  'lifespan.startup.complete' event received from application.", "timestamp": "2021-03-11 23:50:22,357", "service": "mangum", "sampling_rate": 0.0}
{"level": "INFO", "location": "startup:183", "message": "Application startup complete.", "timestamp": "2021-03-11 23:50:22,357", "service": "mangum", "sampling_rate": 0.0}
{"level": "DEBUG", "location": "__call__:63", "message": "HTTP cycle starting.", "timestamp": "2021-03-11 23:50:22,357", "service": "mangum", "sampling_rate": 0.0}
{"level": "INFO", "location": "send:108", "message": "HTTPCycleState.REQUEST:  'http.response.start' event received from application.", "timestamp": "2021-03-11 23:50:22,357", "service": "mangum", "sampling_rate": 0.0}
{"level": "INFO", "location": "send:108", "message": "HTTPCycleState.RESPONSE:  'http.response.body' event received from application.", "timestamp": "2021-03-11 23:50:22,357", "service": "mangum", "sampling_rate": 0.0}
{"level": "INFO", "location": "shutdown:191", "message": "Waiting for application shutdown.", "timestamp": "2021-03-11 23:50:22,358", "service": "mangum", "sampling_rate": 0.0}
{"level": "INFO", "location": "send:129", "message": "LifespanCycleState.SHUTDOWN:  'lifespan.shutdown.complete' event received from application.", "timestamp": "2021-03-11 23:50:22,358", "service": "mangum", "sampling_rate": 0.0}
```

**Comment by tuukkamustonen** [comment]
I would much prefer if Mangum didn't adjust/interfere with logging configuration at all. You can fully adjust the logging from the outside. If Mangum does something, it needs to togglable (so one can disable it).

I wonder if https://github.com/jordaneremieff/mangum/pull/170 (that just got merged) changed the behavior regarding this. The code seems to just discard the `log_config` (and any other extra and unknown) parameter now.

**Comment by four43** [comment]
@aksel, as @tuukkamustonen mentioned we now handle logging pretty minimally (on master) - just by getting the `mangum` logger and that's it. Does that make logging pluggable enough?

**Comment by aksel** [comment]
Makes sense to me! :smile: 

I'll close this issue, as I think it's been resolved.
