### ISSUE TITLE
Add mangum to asgi implementations page in documentation

### ISSUE THREAD

**Issue by emcpow2** [jordaneremieff/mangum#164]
https://asgi.readthedocs.io/en/latest/implementations.html

**Comment by jordaneremieff** [comment]
If someone wants to PR the inclusion there that's fine, but this project is currently listed on https://github.com/florimondmanca/awesome-asgi which seems to have become the de-facto place for ASGI project visibility.

Also, in future please put more consideration before adding issues to the tracker. Even though I'm pretty [lax](https://github.com/jordaneremieff/mangum/blob/main/CONTRIBUTING.md#using-the-issue-tracker) about how the tracker is used, this issue doesn't really describe much and seems like a request for someone (presumably a maintainer) to do additional documentation work in a separate repository.
