### ISSUE TITLE
Support payload format 2.0

### ISSUE THREAD

**Issue by cblegare** [jordaneremieff/mangum#175]
Hello! Thank you for this nice library!

As explained in AWS docs https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html, 

> Format 2.0 doesn't have multiValueHeaders or multiValueQueryStringParameters fields. Duplicate headers are combined with commas and included in the headers field. Duplicate query strings are combined with commas and included in the queryStringParameters field.
>
> Format 2.0 includes a new cookies field. All cookie headers in the request are combined with commas and added to the cookies field. In the response to the client, each cookie becomes a set-cookie header.

It seems to me that version 2.0 is not supported by Mangum

**Comment by koxudaxi** [comment]
@cblegare 
Did you talk about this code?
https://github.com/jordaneremieff/mangum/blob/3f312acb67aac30c07dfb305d3cd1881c59755c4/mangum/handlers/aws_http_gateway.py#L33-L41

**Comment by cblegare** [comment]
@koxudaxi 
Thank you for your response!

It seems I have a bug in my library update process and I was using 0.10.  I stand corrected! thank you again
