### ISSUE TITLE
Lambda Authorizer

### ISSUE THREAD

**Issue by cblegare** [jordaneremieff/mangum#176]
The event received from API Gateway for Lambda Authorizer is either very minimal in case of a TOKEN authorizer, or looks like a normal API Gateway event for a REQUEST authorizer. In fact, the `AbstractHandler.from_trigger` returns an `AwsApiGateway` object, with the path field targeting the downstream called Lambda service.

From my understanding, there is no "resource" or "path" for a Lambda Authorizer, so there is no way for Mangum to find a proper path when creating the request.

I think there could be a way to implement a Lambda Authorizer handler

**Comment by cblegare** [comment]
I've made something work for my specific use case that looks a lot like [that comment](https://github.com/jordaneremieff/mangum/issues/174#issuecomment-816373026), but it is quite hacky.  Maybe providing a simple example in the docs would be a better idea.

**Comment by jordaneremieff** [comment]
I think https://github.com/jordaneremieff/mangum/issues/177 should cover this.
