### ISSUE TITLE
Mangum 0.12 regression: Unable to determine handler from trigger event

### ISSUE THREAD

**Issue by IlyaSukhanov** [jordaneremieff/mangum#193]
A lambda invoke call against mangum 0.11 works fine but with upgrade to version 0.12 same call fails with:

[ERROR] TypeError: Unable to determine handler from trigger event
Traceback (most recent call last):
  File "/var/task/mangum/adapter.py", line 86, in __call__
    handler = AbstractHandler.from_trigger(
  File "/var/task/mangum/handlers/abstract_handler.py", line 113, in from_trigger
    raise TypeError("Unable to determine handler from trigger event")
START RequestId: 7d86054b-94df-4bba-b5e0-60106f2d9fa9 Version: $LATEST

**Comment by luizsfer** [comment]
I have same problem from @IlyaSukhanov 

`[ERROR] TypeError: Unable to determine handler from trigger event
Traceback (most recent call last):
  File "/var/task/mangum/adapter.py", line 86, in __call__
    handler = AbstractHandler.from_trigger(
  File "/var/task/mangum/handlers/abstract_handler.py", line 113, in from_trigger
    raise TypeError("Unable to determine handler from trigger event")`

I solved making a downgrade to 0.11.0 and worked fine.

**Comment by jordaneremieff** [comment]
Hi @IlyaSukhanov and @luizsfer,

Could you provide more details about your configurations? Specifically, are you using HTTP or API Gateway?

**Comment by IlyaSukhanov** [comment]
Hello @jordaneremieff

My particular use case is not exactly standard. I'm emulating API Gateway Rest API as a proxy integration.  This is based of [lambda proxy integrations](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-input-format) document, for reference [my implementation](https://github.com/IlyaSukhanov/lambda-requests/blob/master/lambda_requests/lambda_request.py).

After looking at whats changed in Mangum, its clear that the root cause is that "resource" is [now (0.12) required](https://github.com/jordaneremieff/mangum/blob/main/mangum/handlers/abstract_handler.py#L106). Without it Magnum cannot determine that its an AwsApiGateway event. Passing along this attribute in my implementation makes things work.

I'm not aware of existence of AWS documentation describing what concretely differentiates the varying types of Lambda events (if this documentation does exist, I'd greatly appreciate a link), and as such will attribute the bug to lambda-requests rather than to that of Mangum. Sorry about the premature bug report! I hope this may serve as useful information to anyone who encounters similar issues.

Thank you for providing this wonderful library!

**Comment by jordaneremieff** [comment]
@luizsfer is your issue similar or should I close this off?

**Comment by jordaneremieff** [comment]
I will close this unless someone else confirms this is a widespread issue for common deployments.
