### ISSUE TITLE
Argument "log_level" to "Mangum" has incompatible type "str"; expected "Dict[str, Any]" (Mangum 0.12)

### ISSUE THREAD

**Issue by charlax** [jordaneremieff/mangum#195]
I'm noticing the following regression with Mangum 0.12 and mypy (0.11 works fine):

```python
handler = mangum.adapter.Mangum(
    SentryAsgiMiddleware(app), lifespan="auto", log_level=config.log_level.lower()
)
```

With 0.12:

```text
error: Argument "log_level" to "Mangum" has incompatible type "str"; expected "Dict[str, Any]"  [arg-type]
        SentryAsgiMiddleware(app), lifespan="auto", log_level=config.log_level.lower()
```

No error with 0.11

Using mypy 0.910 (latest as of writing)

**Comment by charlax** [comment]
It looks like this option is not used anymore, perhaps it should be added as a (minor) breaking change to the docs, and removed from `docs/adapter.md`?

**Comment by jordaneremieff** [comment]
Yep that's been removed and logging is no longer configured in Mangum itself - docs need an update.

**Comment by jordaneremieff** [comment]
Updated.
