### ISSUE TITLE
boto3 requirement

### ISSUE THREAD

**Issue by rpf3** [jordaneremieff/mangum#196]
I'm trying to use Mangum in my project and running across an error that seems to have to do with a missing boto3 requirement.  When I run the following code:

``` python
from fastapi import FastAPI
from mangum import Mangum

app = FastAPI()

@app.get("/")
async def root():
    return {"message": "Hello World!"}

handler = Mangum(app)
```

I get the following error:

> ModuleNotFoundError: No module named 'boto3'

The stack trace is pointing to this line of code:

https://github.com/jordaneremieff/mangum/blob/1f543bce883890f6d2487bd141e3f735f4e8ca56/mangum/backends/__init__.py#L14

If I simply add boto3 as a dependency to my project everything works as expected.  I see that in in #115 boto3 was made optional but as far as I can tell that has been removed.

**Comment by jordaneremieff** [comment]
Hi @rpf3, thanks for the report. I've released 0.12.1 to remove this requirement.
