### ISSUE TITLE
mypy - Argument "api_gateway_base_path" to "Mangum" has incompatible type "str"; expected "Dict[str, Any]"

### ISSUE THREAD

**Issue by matthieudesprez** [jordaneremieff/mangum#201]
I upgraded from 0.10.0 to 0.12.2 and now I got this error from mypy

From what I see it must come from #170 and now mypy doesn't have any way to tell that it can accept an argument named api_gateway_base_path

**Comment by DanLipsitt** [comment]
To reproduce:

**example.py**:
```python
from mangum import Mangum
from fastapi import FastAPI

handler = Mangum(FastAPI(), api_gateway_base_path="/foo")
```

```shellsession
❯ mypy example.py
example.py:4: error: Argument "api_gateway_base_path" to "Mangum" has incompatible type "str"; expected "Dict[str, Any]"
Found 1 error in 1 file (checked 1 source file)
```

**Comment by relsunkaev** [comment]
[Relevant PEP 484 section](https://www.python.org/dev/peps/pep-0484/#arbitrary-argument-lists-and-default-argument-values)
