### ISSUE TITLE
Allow Mangum to remove certain aws reponse headers from api gateway response

### ISSUE THREAD

**Issue by amieka** [jordaneremieff/mangum#202]
Problem:
Currently `Mangum` injects the following headers in the api gateway response for an aws lambda integration

```
x-amz-apigw-id
x-amzn-requestid 
x-amzn-trace-id
```

This exposes additional information that the client doesn't need to know.

Proposal:

Allow Mangum to take optional parameter say `exclude_header_keys=[]` at the application mounting step.

An Example of that would look like.

```python

from fastapi import FastAPI

app = FastAPI()

handler = Mangum(app, exclude_header_keys=[]
```

**Comment by jordaneremieff** [comment]
Hi @amieka,

I've given this some thought and decided it should okay to include this new parameter - let's go with a new parameter named `exclude_headers`.

Would you be able to create a PR?
