### ISSUE TITLE
Mock AWS Gateway Response back into Mangum

### ISSUE THREAD

**Issue by dovedevic** [jordaneremieff/mangum#205]
I am writing an application that has a method that takes up to 3 minutes to complete. Because of APIGateway's limitations on the maximum allowed lifetime of lambda invocations, I've opted to architect the following workaround:

When the method is called, call a separate lambda asynchronously to perform the task, give it an ID, and return the ID to the user to later fetch results.

When I transferred over to using FastAPI and Mangum, I figured I could "mock" an API Gateway event invocation so that way I can upload one large lambda instead of multiple.

So in my code for the user-facing method, I call this function
```
def construct_ray_payload(request: Request, resource: str, path_params: dict, body: dict, method: str='POST'):
    """Construct a remapped event context for a new path resource using the provided requests prior event context"""

    context = request.scope['aws.event']['requestContext'] if "aws.event" in request.scope and 'requestContext' in request.scope['aws.event'] else {}
    context['resourcePath'] = resource
    context['httpMethod'] = method
    context['path'] = resource.format(**path_params)

    event = {
        'resource': resource,
        'path': resource.format(**path_params),
        'httpMethod': method,
        'headers': request.scope['aws.event']['headers'] if "aws.event" in request.scope and 'headers' in request.scope['aws.event'] else {},
        'queryStringParameters': None,
        'multiValueQueryStringParameters': None,
        'pathParameters': path_params,
        'requestContext': context,
        'body': json.dumps(body),  # mangum throws a "dict not encodable" error if were not s-dumping here
        'isBase64Encoded': False
    }
    return event
```

and subsequently call the very same lambda asynchronously with the payload being what is returned here. From debug logs, I can verify Magnum receiving the request in the adapter call dunder and AwsApiGateway abstract handler request method, however nothing is invoked via FastAPI, despite the path, path vars, and body being the type it expects. 

There seems to be no advanced debug logging in Mangum to further dig into if a FastAPI router is being invoked by mangum for the request.

Any thoughts or ideas? Is this a Mangum error or FastAPI configuration error?

**Comment by jordaneremieff** [comment]
Hi @dovedevic, I'll need to know more about what your handler and deployment configuration looks like to understand if this is an issue in Mangum or FastAPI, or potentially something specific to your implementation/deployment configuration.

Could you post a minimal example demonstrating a handler function and invocation method(s) to reproduce this?

**Comment by dovedevic** [comment]
Super late on the followup, but I spent a few afternoons digging around both Mangum and FastAPI code to realize that when calling this method, the `context["path"]` and `context['requestContext']['path']` was not including a trailing slash, when my FastAPI configuration was not configured to automatically redirect. Updating this fixed the issue. 

I still believe additional logging (at the DEBUG level) should be implemented to trace requests handled through Mangum, perhaps I can send out a PR eventually for that. Regardless this issues is resolved and I'll close.
