### ISSUE TITLE
ALB Triggered Lambda

### ISSUE THREAD

**Issue by romcab** [jordaneremieff/mangum#206]
Question:

Is there a plan to support ALB triggered lambda? would like to convert flask using fastapi due to performance.

**Comment by richieadler** [comment]
I would also be interested in this possibility.

**Comment by jordaneremieff** [comment]
Could you provide more detail on what you would like to see here and what would be required? There are no plans for this currently, but happy to consider any proposals with sufficient detail.

**Comment by dmzio** [comment]
I assume it's about https://docs.aws.amazon.com/lambda/latest/dg/services-alb.html - to allow this wrapper to handle ALB-specific events. There's similar project for WSGI, which does so - https://github.com/adamchainz/apig-wsgi

**Comment by jordaneremieff** [comment]
@dmzio I think you're right. I think I will close this since it appears that the issue refers to the ALB support that was added relatively recently.
