### ISSUE TITLE
Improve Access Logs

### ISSUE THREAD

**Issue by kevinmic** [jordaneremieff/mangum#210]
We are moving some of our django applications to run inside a lambda. When we did so we lost access logs and gained logs that don't have much information. It would be useful if the Mangum Request/Response had additional log information or a mechanism was added to make logging access logs easy.

Example.  WSGI access logs
```
GET /v2/resource HTTP/1.1" 200 686
GET /v2/resource/123 HTTP/1.1" 200 686
POST /v2/resource/123 HTTP/1.1" 400 128
```

Mangum Access Logs for the same thing
```
HTTPCycleState.REQUEST:  'http.response.start' event received from application.
HTTPCycleState.RESPONSE:  'http.response.body' event received from application.
HTTPCycleState.REQUEST:  'http.response.start' event received from application.
HTTPCycleState.RESPONSE:  'http.response.body' event received from application.
HTTPCycleState.REQUEST:  'http.response.start' event received from application.
HTTPCycleState.RESPONSE:  'http.response.body' event received from application.
```

**Comment by jordaneremieff** [comment]
Yep, good point. The existing logs were mostly to assist with the initial development of the ASGI event flow (debugging really), but otherwise they are not particularly insightful.

Do you have any ideas for how to approach this?

**Comment by guaccc** [comment]
@kevinmic have you tried logging the raw lambda request via `aws.event`?

## request
```
class AWSLoggingMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request, call_next):
        response = await self.call_next(request)

        log_data = {
            'request': request.scope.get('aws.event'),
        }

        # send to cloudwatch or kinesis...
        logger.info({log_data})

        return response
```

Unfortunately for logging the response with body etc I've been having more of a challenge and certainly wish there was a built-in way to easily access it...
https://github.com/encode/starlette/issues/874
https://stackoverflow.com/questions/64115628/get-starlette-request-body-in-the-middleware-context

**Comment by kevinmic** [comment]
Sorry, I moved companies and so I am not using this currently. We looked at a number of options and had work arounds. It would simply have been convient to be able to configure it directly.

**Comment by guaccc** [comment]
@kevinmic agree it'd be nice w/o wrangling a bit..

**Comment by aminalaee** [comment]
@jordaneremieff I can help with this. Is it clear what needs to be done here? I mean is it just the log information to be changed? Can that be a good start?

**Comment by hoIIer** [comment]
@aminalaee the request data is already available via `request.scope.get('aws.event')`, the response data just has to be parsed out... if it were available already that would be one step less for the end user

**Comment by aminalaee** [comment]
@hoIIer After taking a look at Nginx and Gunicorn logs, I don't think we need to log request/response body. What they do is that log only when sending response with information about that.
I did the same here but if you have any feedback please review that PR.

**Comment by hoIIer** [comment]
@aminalaee yeah I mean the request body is already available via request.scope['aws.event'], the body has to be parsed out as above. It'd be more convenient to have them both available e.g. request.body, response.body, but doesn't necessarily have to be built in.

It's helpful for full req/resp logging which e.g. I'm using for backend analytics
