### ISSUE TITLE
Lost response cookies on AWS HTTP Gateway with v2.0 payload.

### ISSUE THREAD

**Issue by IlyaSukhanov** [jordaneremieff/mangum#215]
When responding with multiple cookies over AWS HTTP Gateway v2.0 the cookies get lost. This is because Mangum packs them into multiValueHeaders which are no longer supported in v2.0. The new specification [[1]](https://aws.amazon.com/blogs/compute/building-better-apis-http-apis-now-generally-available/) [[2]](https://medium.com/@lancers/amazon-api-gateway-explaining-lambda-payload-version-2-0-in-http-api-24b0b4db5d36) calls for:

* Passing response cookies in `cookies` element
* Passing multivalue headers as comma separated strings in `headers` element

**Comment by jordaneremieff** [comment]
Closed by https://github.com/jordaneremieff/mangum/pull/216
