### ISSUE TITLE
Support aws-lambda-powertools-python Tracer.capture_lambda_handler decorator

### ISSUE THREAD

**Issue by zlalvani** [jordaneremieff/mangum#222]
[aws-lambda-powertools-python](https://github.com/awslabs/aws-lambda-powertools-python) has a lambda tracing library in its `tracing` module, which provides a decorator intended to be used on lambda handler functions: 

```
tracer = Tracer()

@tracer.capture_lambda_handler
def handle(event, context):
  ...
```

However, it expects the callable it wraps to have a `__name__` attribute, as we can see inside of the `capture_lambda_handler` code: 

```lambda_handler_name = lambda_handler.__name__```

Since mangum only defines `__call__` and objects don't inherit the `__name__` attribute of their class, this fails with an `AttributeError`:
```
AttributeError: 'Mangum' object has no attribute '__name__'
```

One possible solution is to create a `@property` method in the Mangum class that returns the wrapped function's `__name__`, but I don't know if that's the best solution.

**Comment by jordaneremieff** [comment]
Hey @zlalvani, I understand the gist of the issue here, thanks for the detailed description - let’s explore the options here.

To start, can you provide any info on if this is a significant limitation of Mangum/something atypical of similar libraries, or is the tracing behaviour of the powertools lib doing anything particularly “special” that might be better accommodated without modifying Mangum itself?

**Comment by jordaneremieff** [comment]
@zlalvani would implementing the handler as a function and returning the Mangum callable work here?

**Comment by zlalvani** [comment]
I can define a handler function like that, though I wasn't sure if that's the intended solution for situations like this. 

I'm not sure if there's actually a defined specification that must be met for the `Callable` type besides implementing `__call__`. The builtin `callable()` returns True for Mangum objects, so I think it's safe to assume it meets the specification. However, if it turns out that `__name__` is part of that standard, then I think it makes sense to add it to mangum.

Looks like this workaround would be the best approach, and perhaps making an issue with the powertools team to mention that not every `Callable` has a `__name__`.

**Comment by jordaneremieff** [comment]
I think you're right. The best solution at this point seems to be the workaround and to discuss it further with that project. I'll close for now, but if it's later determined that we're incorrect about the `Callable` type, then feel free to reopen and we can look at resolving it here.
