### ISSUE TITLE
Unable to determine handler from trigger event

### ISSUE THREAD

**Issue by ArtemSam23** [jordaneremieff/mangum#237]
I made a project with python package and only main.py with the Hello World get request from magnum docs. Then I made a deploy from GitHub actions. Then I tested api gateway and get this error:
```
{
  "errorMessage": "Unable to determine handler from trigger event",
  "errorType": "TypeError",
  "requestId": "ee98ad16-d50b-4c44-a83d-e44bf534aa5c",
  "stackTrace": [
    "  File \"/var/task/mangum/adapter.py\", line 83, in __call__\n    handler = AbstractHandler.from_trigger(\n",
    "  File \"/var/task/mangum/handlers/abstract_handler.py\", line 116, in from_trigger\n    raise TypeError(\"Unable to determine handler from trigger event\")\n"
  ]
}
```
I've been trying to solve this problem, but nothing really worked.
This is my [project](https://github.com/ArtemSam23/AWS-FastApi/tree/develop) check develop branch

**Comment by jordaneremieff** [comment]
Hi, please see https://github.com/jordaneremieff/mangum/discussions/218. This is likely related to the data you are including when invoking your lambda function.
