### ISSUE TITLE
Plugging FastAPI into Mangum raises mypy type checking error

### ISSUE THREAD

**Issue by ImreC** [jordaneremieff/mangum#247]
I am trying to use Magnum in combination with FastAPI, but when I type check with mypy, I get the following error: 

```
main.py:12: error: Argument 1 to "Mangum" has incompatible type "FastAPI"; expected "ASGIApp"
main.py:12: note: Following member(s) of "FastAPI" have conflicts:
main.py:12: note:     Expected:
main.py:12: note:         def __call__(self, scope: Union[HTTPScope, LifespanScope], receive: Callable[[], Awaitable[Union[HTTPRequestEvent, HTTPDisconnectEvent, LifespanStartupEvent, LifespanShutdownEvent]]], send: Callable[[Union[HTTPResponseStartEvent, HTTPResponseBodyEvent, HTTPDisconnectEvent, LifespanStartupCompleteEvent, LifespanStartupFailedEvent, LifespanShutdownCompleteEvent, LifespanShutdownFailedEvent]], Awaitable[None]]) -> Coroutine[Any, Any, None]
main.py:12: note:     Got:
main.py:12: note:         def __call__(self, scope: MutableMapping[str, Any], receive: Callable[[], Awaitable[MutableMapping[str, Any]]], send: Callable[[MutableMapping[str, Any]], Awaitable[None]]) -> Coroutine[Any, Any, None]
Found 1 error in 1 file (checked 1 source file)
```
It seems that the types are defined in an incompatible way. Is this known and is there any way to resolve this? I came across https://github.com/jordaneremieff/mangum-examples/issues/2 so this seems fixed two years ago, but can't get the type check to succeed currently. What am I doing wrong? 

requirements.txt
```
anyio==3.5.0; python_full_version >= '3.6.2'
fastapi==0.75.0
idna==3.3; python_version >= '3.5'
mangum==0.14.1
pydantic==1.9.0; python_full_version >= '3.6.1'
sniffio==1.2.0; python_version >= '3.5'
starlette==0.17.1; python_version >= '3.6'
typing-extensions==4.1.1; python_version >= '3.6'
```

Python version 3.8 (also tried with 3.9 and 3.10)

**Comment by jordaneremieff** [comment]
I added more specific annotations recently. I'll have a look at this when I get a chance.

**Comment by relsunkaev** [comment]
It's the `TypedDict` usage. `MutableMapping` (what Starlette uses for its `Scope` and `Message` types) is not compatible with any `TypedDict`. Only `Mapping[str, Any]` and `Mapping[str, object]` are compatible with `TypedDict`.

There is currently [a PR](https://github.com/encode/starlette/pull/1374) for Starlette to switch to [asgiref](https://github.com/django/asgiref/tree/main/asgiref) for typing ASGI events. Once that PR merged, this issue will be alleviated for Starlette. However, I don't imagine FastAPI will be updating Starlette anytime soon considering it's current level of support.

**Comment by jordaneremieff** [comment]
What are the options here? 

Ideally that MR to Starlette would be merged and ultimately picked up in FastAPI because the more specific types provide more useful information. However, given that most users of Mangum are likely using one of these libraries then I'd be open to a PR reverting to the original types to support them specifically, though I'd prefer if there was some way to workaround this.

**Comment by jordaneremieff** [comment]
I think I will go ahead and just relax the annotations here. I'm noticing that the `Lifespan` scope is conflicting with the `HTTPScope` when accessing it in the application.

**Comment by jordaneremieff** [comment]
Changed in https://github.com/jordaneremieff/mangum/pull/259
