### ISSUE TITLE
Option to disable websockets? (Websocket protocol import is slow)

### ISSUE THREAD

**Issue by benharris-conversica** [jordaneremieff/mangum#252]
I was doing some profiling to try to speed up my lambda cold starts when I noticed `mangum.protocols.websockets` is taking up the majority of the import time for Mangum (0.25s / 0.4s total on my system, see below for details). I'd like to be able to disable this import to speed things up. Is it possible to do something like https://github.com/jordaneremieff/mangum/pull/197 to make websocket support optional?

Profiling details (using https://github.com/nschloe/tuna to visualize):
```
python -X importtime -c 'from mangum import Mangum' 2> mangum.log
tuna mangum.log
```

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/42979826/158692418-e67eb698-2086-4e40-b4c3-57dc9c7468fe.png">

**Comment by jordaneremieff** [comment]
@benharris-conversica websocket support was removed. You can upgrade your version to avoid this.

**Comment by benharris-conversica** [comment]
Whoops, I was looking on the releases page on https://mangum.io/, didn't realize there was a newer version. I can confirm this fixes the issue for me, mangum loads 2x faster in the latest version:

![image](https://user-images.githubusercontent.com/42979826/158854040-a1921e15-0cb0-453e-87ba-cf663c44e725.png)
