### ISSUE TITLE
Support lambda function url

### ISSUE THREAD

**Issue by dorinclisu** [jordaneremieff/mangum#258]
Starting with April 2022, AWS supports a new and simplified way of using your lambda function as an API. https://docs.aws.amazon.com/lambda/latest/dg/lambda-urls.html

I think it should be possible to adapt mangum to support the specific event mapping for function url.

**Comment by jordaneremieff** [comment]
As far as I can tell so far there shouldn't be anything specific required, according to https://docs.aws.amazon.com/lambda/latest/dg/urls-invocation.html:

>The request and response event formats follow the same schema as the [Amazon API Gateway payload format version 2.0](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html#http-api-develop-integrations-lambda.proxy-format).

Assuming this just works with the current handler without adjustments, then I think only the documentation and handler naming/comments might need to be updated. 

Or is the something I am missing that would require a unique handler?

**Comment by jordaneremieff** [comment]
It seems to be working fine with the HTTP API handler from my testing. Let me know if you run into issues.
