### ISSUE TITLE
Using serverless warmup plugin with mangum

### ISSUE THREAD

**Issue by ApurvaMisra** [jordaneremieff/mangum#266]
What would be the best way for Mangum to respond based on the event source? I want to modify the event handler, such that it responds without doing any processing if the event is from the below source	
{
  "Event": {
    "source": "serverless-plugin-warmup"
  }
}

The aim is to reduce the time the lambda is occupied for when invoked by the warmer lambda.
Here is the link for the plugin: https://www.serverless.com/plugins/serverless-plugin-warmup 
![image](https://user-images.githubusercontent.com/22544948/177880234-3d13f160-7d13-4d87-bf68-72d94b478489.png)

**Comment by jordaneremieff** [comment]
Hi @ApurvaMisra, this can be accomplished by using a function that returns the handler instance as demonstrated [here](https://mangum.io/adapter/#creating-an-aws-lambda-handler).

See also [this](https://github.com/jordaneremieff/mangum/issues/91#issuecomment-599014240) comment for a similar use-case that may help clarify things further.
