### ISSUE TITLE
FYI: documentation is not available at mangum.io

### ISSUE THREAD

**Issue by py-alex** [jordaneremieff/mangum#294]
FYI: documentation is not available at mangum.io ....

In README.md :  
```
Documentation: https://mangum.io/
```

above link does not work with https

http://mangum.io/ goes to parked domain page

**Comment by followben** [comment]
cc @jordaneremieff prob a reasonably significant one to check out

**Comment by jordaneremieff** [comment]
Didn't notice the notification for the domain expiry. I renewed it at this point. Need to fix up the DNS.

**Comment by jordaneremieff** [comment]
Should be showing again.

**Comment by hakonlo** [comment]
@jordaneremieff I'm pretty sure that the domain is parked again, though the message on the site is cryptic.

> **No sponsors**
> mangum.io currently does not have any sponsors for you.
