### ISSUE TITLE
Dealing with long running client

### ISSUE THREAD

**Issue by zhavir** [jordaneremieff/mangum#320]
Hello, do you know which is the beast way to deal with a long-running client? I'd like to use boto3 client within an api call, but it is taking forever every time to setup the session and making the call. Any suggestion? where is the best place where to initialize the boto3 session?

**Comment by 25thbamofthetower** [comment]
AWS has docs about where to place it. It's usually outside of the Lambda handler function. It's usually the first search results. But I think what you're seeing might be the Lambda coldstart.

**Comment by zhavir** [comment]
yes, more or less. I've put my client init outside the handler. But seems like that, even so, the first call to SNS (that is my case) is taking forever (3.5 secs). Afterward, consecutive calls are taking 200 ms. Interestingly, I've tried to set up a CloudWatch event that is always warming the lambda function (more or less), with this trick I was able to decrease the timing to 1.2 secs on the first call,  consecutive calls are still taking 200 ms. To reduce the time also for the first call I was forced to call the list topic right after the initialization of the Boto client

**Comment by nitsujri** [comment]
> To reduce the time also for the first call I was forced to call the list topic right after the initialization of the Boto client

This is cold start problem, right? After you deploy your AWS Lambda container? When you deploy a new version, it takes 3.5 to 5 seconds to cold start and fully answer a client?

If it is, we deal with this problem via blue/green deployments with CodeDeploy. For us, we use the CDK, specifically 

1. [`aws_sam.CfnFunction`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_sam.CfnFunction.html).
  - This is **not** lambda.cfnfunction.
2. This allows us to use the pre-deployment Validation. via `deploymentPreference: {hooks: { preTraffic: ... }}`
3. `preTraffic` is the same lambda but with a different entrypoint. The entry point is a special "pre-warming" hook that fires 5x to get around the cold start problem you mentioned.

This way you can pre-warm the new version and only switch traffic to the new version after the cold start has been "dealt with"
